name: docker-build

on:
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        tap:
          - mysql
          - postgres
          - oracle
          - s3-csv
          - kafka
        target:
          - postgres
          - redshift
          - snowflake
          - s3-csv
    steps:
      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: dirathea/pipelinewise:${{ steps.vars.outputs.tag }}-${{ matrix.tap }}-${{ matrix.target }}
          build-args: |
            connectors=tap-${{ matrix.tap }},target-${{ matrix.target }},transform-field
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}